# Generated by Django 6.0.5 on 2026-05-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
